apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: caos-operator-role
rules:
  - apiGroups: ["", "apps"]
    resources: ["services", "deployments", "pods"]
    verbs: ["get", "watch", "list", "create", "delete", "update"]

  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]

  - apiGroups: ["caos.puravida.com"]
    resources: ["monkeys"]
    verbs: ["*"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: caos-operator-sa

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: caos-operator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: caos-operator-role
subjects:
  - kind: ServiceAccount
    name: caos-operator-sa
    namespace: default

